/*************************************************************************************************

Welcome to Baml! To use this generated code, please run one of the following:

$ npm install @boundaryml/baml
$ yarn add @boundaryml/baml
$ pnpm add @boundaryml/baml

*************************************************************************************************/

// This file was generated by BAML: do not edit it. Instead, edit the BAML
// files and re-generate this code.
//
/* eslint-disable */
// tslint:disable
// @ts-nocheck
// biome-ignore format: autogenerated code
import type { Audio, BamlCtxManager, BamlRuntime, ClientRegistry, Collector, FunctionResult, Image } from "@boundaryml/baml"
import { BamlStream, type HTTPRequest, toBamlError } from '@boundaryml/baml';
import { AsyncHttpRequest, AsyncHttpStreamRequest } from './async_request';
import {
  DO_NOT_USE_DIRECTLY_UNLESS_YOU_KNOW_WHAT_YOURE_DOING_CTX,
  DO_NOT_USE_DIRECTLY_UNLESS_YOU_KNOW_WHAT_YOURE_DOING_RUNTIME,
} from './globals';
import { LlmResponseParser, LlmStreamParser } from './parser';
import type { partial_types } from './partial_types';
import type TypeBuilder from './type_builder';
import type { Check, Checked, RecursivePartialNull as MovedRecursivePartialNull } from './types';
import type * as types from './types';
import type {
  CurrentStateAnalysis,
  Desire,
  DesiresExtractionResult,
  DetectedEmotion,
  EmergingPattern,
  EmotionAnalysis,
  EmotionMetadata,
  EmotionalExtractionResult,
  EmotionalTransition,
  EventTriggeredChange,
  IdentityComponent,
  IdentityExtractionResult,
  PADValues,
  PersonalityContext,
  PersonalityDynamicsAnalysis,
  PersonalityObservation,
  PersonalityObservationResult,
  PersonalityTrait,
  PhysicalAttribute,
  PhysicalExtractionResult,
  Preference,
  Resume,
  SpeechExtractionResult,
  SpeechPattern,
  StateDeviation,
  TemporalDynamics,
  VariabilityPattern,
} from './types';

/**
 * @deprecated Use RecursivePartialNull from 'baml_client/types' instead.
 */
export type RecursivePartialNull<T> = MovedRecursivePartialNull<T>;

type BamlCallOptions = {
  tb?: TypeBuilder;
  clientRegistry?: ClientRegistry;
  collector?: Collector | Collector[];
};

export class BamlAsyncClient {
  private runtime: BamlRuntime;
  private ctxManager: BamlCtxManager;
  private streamClient: BamlStreamClient;
  private httpRequest: AsyncHttpRequest;
  private httpStreamRequest: AsyncHttpStreamRequest;
  private llmResponseParser: LlmResponseParser;
  private llmStreamParser: LlmStreamParser;
  private bamlOptions: BamlCallOptions;

  constructor(runtime: BamlRuntime, ctxManager: BamlCtxManager, bamlOptions?: BamlCallOptions) {
    this.runtime = runtime;
    this.ctxManager = ctxManager;
    this.streamClient = new BamlStreamClient(runtime, ctxManager, bamlOptions);
    this.httpRequest = new AsyncHttpRequest(runtime, ctxManager);
    this.httpStreamRequest = new AsyncHttpStreamRequest(runtime, ctxManager);
    this.llmResponseParser = new LlmResponseParser(runtime, ctxManager);
    this.llmStreamParser = new LlmStreamParser(runtime, ctxManager);
    this.bamlOptions = bamlOptions || {};
  }

  withOptions(bamlOptions: BamlCallOptions) {
    return new BamlAsyncClient(this.runtime, this.ctxManager, bamlOptions);
  }

  get stream() {
    return this.streamClient;
  }

  get request() {
    return this.httpRequest;
  }

  get streamRequest() {
    return this.httpStreamRequest;
  }

  get parse() {
    return this.llmResponseParser;
  }

  get parseStream() {
    return this.llmStreamParser;
  }

  async AnalyzeEmotions(
    text: string,
    __baml_options__?: BamlCallOptions,
  ): Promise<EmotionAnalysis> {
    try {
      const options = { ...this.bamlOptions, ...(__baml_options__ || {}) };
      const collector = options.collector
        ? Array.isArray(options.collector)
          ? options.collector
          : [options.collector]
        : [];
      const raw = await this.runtime.callFunction(
        'AnalyzeEmotions',
        {
          text: text,
        },
        this.ctxManager.cloneContext(),
        options.tb?.__tb(),
        options.clientRegistry,
        collector,
      );
      return raw.parsed(false) as EmotionAnalysis;
    } catch (error) {
      throw toBamlError(error);
    }
  }

  async AnalyzePersonalityDynamics(
    recentObservations: PersonalityObservation[],
    historicalContext?: string | null,
    __baml_options__?: BamlCallOptions,
  ): Promise<PersonalityDynamicsAnalysis[]> {
    try {
      const options = { ...this.bamlOptions, ...(__baml_options__ || {}) };
      const collector = options.collector
        ? Array.isArray(options.collector)
          ? options.collector
          : [options.collector]
        : [];
      const raw = await this.runtime.callFunction(
        'AnalyzePersonalityDynamics',
        {
          recentObservations: recentObservations,
          historicalContext: historicalContext ?? null,
        },
        this.ctxManager.cloneContext(),
        options.tb?.__tb(),
        options.clientRegistry,
        collector,
      );
      return raw.parsed(false) as PersonalityDynamicsAnalysis[];
    } catch (error) {
      throw toBamlError(error);
    }
  }

  async EstimatePADValues(
    emotionName: string,
    context: string,
    __baml_options__?: BamlCallOptions,
  ): Promise<PADValues> {
    try {
      const options = { ...this.bamlOptions, ...(__baml_options__ || {}) };
      const collector = options.collector
        ? Array.isArray(options.collector)
          ? options.collector
          : [options.collector]
        : [];
      const raw = await this.runtime.callFunction(
        'EstimatePADValues',
        {
          emotionName: emotionName,
          context: context,
        },
        this.ctxManager.cloneContext(),
        options.tb?.__tb(),
        options.clientRegistry,
        collector,
      );
      return raw.parsed(false) as PADValues;
    } catch (error) {
      throw toBamlError(error);
    }
  }

  async ExtractDesiresAndBoundaries(
    content: string,
    __baml_options__?: BamlCallOptions,
  ): Promise<DesiresExtractionResult> {
    try {
      const options = { ...this.bamlOptions, ...(__baml_options__ || {}) };
      const collector = options.collector
        ? Array.isArray(options.collector)
          ? options.collector
          : [options.collector]
        : [];
      const raw = await this.runtime.callFunction(
        'ExtractDesiresAndBoundaries',
        {
          content: content,
        },
        this.ctxManager.cloneContext(),
        options.tb?.__tb(),
        options.clientRegistry,
        collector,
      );
      return raw.parsed(false) as DesiresExtractionResult;
    } catch (error) {
      throw toBamlError(error);
    }
  }

  async ExtractEmotionalJourney(
    messages: string[],
    __baml_options__?: BamlCallOptions,
  ): Promise<EmotionalTransition[]> {
    try {
      const options = { ...this.bamlOptions, ...(__baml_options__ || {}) };
      const collector = options.collector
        ? Array.isArray(options.collector)
          ? options.collector
          : [options.collector]
        : [];
      const raw = await this.runtime.callFunction(
        'ExtractEmotionalJourney',
        {
          messages: messages,
        },
        this.ctxManager.cloneContext(),
        options.tb?.__tb(),
        options.clientRegistry,
        collector,
      );
      return raw.parsed(false) as EmotionalTransition[];
    } catch (error) {
      throw toBamlError(error);
    }
  }

  async ExtractEmotionalPatterns(
    content: string,
    __baml_options__?: BamlCallOptions,
  ): Promise<EmotionalExtractionResult> {
    try {
      const options = { ...this.bamlOptions, ...(__baml_options__ || {}) };
      const collector = options.collector
        ? Array.isArray(options.collector)
          ? options.collector
          : [options.collector]
        : [];
      const raw = await this.runtime.callFunction(
        'ExtractEmotionalPatterns',
        {
          content: content,
        },
        this.ctxManager.cloneContext(),
        options.tb?.__tb(),
        options.clientRegistry,
        collector,
      );
      return raw.parsed(false) as EmotionalExtractionResult;
    } catch (error) {
      throw toBamlError(error);
    }
  }

  async ExtractIdentityComponents(
    content: string,
    __baml_options__?: BamlCallOptions,
  ): Promise<IdentityExtractionResult> {
    try {
      const options = { ...this.bamlOptions, ...(__baml_options__ || {}) };
      const collector = options.collector
        ? Array.isArray(options.collector)
          ? options.collector
          : [options.collector]
        : [];
      const raw = await this.runtime.callFunction(
        'ExtractIdentityComponents',
        {
          content: content,
        },
        this.ctxManager.cloneContext(),
        options.tb?.__tb(),
        options.clientRegistry,
        collector,
      );
      return raw.parsed(false) as IdentityExtractionResult;
    } catch (error) {
      throw toBamlError(error);
    }
  }

  async ExtractPersonalityObservations(
    content: string,
    recentHistory?: string | null,
    __baml_options__?: BamlCallOptions,
  ): Promise<PersonalityObservationResult> {
    try {
      const options = { ...this.bamlOptions, ...(__baml_options__ || {}) };
      const collector = options.collector
        ? Array.isArray(options.collector)
          ? options.collector
          : [options.collector]
        : [];
      const raw = await this.runtime.callFunction(
        'ExtractPersonalityObservations',
        {
          content: content,
          recentHistory: recentHistory ?? null,
        },
        this.ctxManager.cloneContext(),
        options.tb?.__tb(),
        options.clientRegistry,
        collector,
      );
      return raw.parsed(false) as PersonalityObservationResult;
    } catch (error) {
      throw toBamlError(error);
    }
  }

  async ExtractPhysicalAttributes(
    content: string,
    __baml_options__?: BamlCallOptions,
  ): Promise<PhysicalExtractionResult> {
    try {
      const options = { ...this.bamlOptions, ...(__baml_options__ || {}) };
      const collector = options.collector
        ? Array.isArray(options.collector)
          ? options.collector
          : [options.collector]
        : [];
      const raw = await this.runtime.callFunction(
        'ExtractPhysicalAttributes',
        {
          content: content,
        },
        this.ctxManager.cloneContext(),
        options.tb?.__tb(),
        options.clientRegistry,
        collector,
      );
      return raw.parsed(false) as PhysicalExtractionResult;
    } catch (error) {
      throw toBamlError(error);
    }
  }

  async ExtractResume(resume: string, __baml_options__?: BamlCallOptions): Promise<Resume> {
    try {
      const options = { ...this.bamlOptions, ...(__baml_options__ || {}) };
      const collector = options.collector
        ? Array.isArray(options.collector)
          ? options.collector
          : [options.collector]
        : [];
      const raw = await this.runtime.callFunction(
        'ExtractResume',
        {
          resume: resume,
        },
        this.ctxManager.cloneContext(),
        options.tb?.__tb(),
        options.clientRegistry,
        collector,
      );
      return raw.parsed(false) as Resume;
    } catch (error) {
      throw toBamlError(error);
    }
  }

  async ExtractSpeechPatterns(
    content: string,
    __baml_options__?: BamlCallOptions,
  ): Promise<SpeechExtractionResult> {
    try {
      const options = { ...this.bamlOptions, ...(__baml_options__ || {}) };
      const collector = options.collector
        ? Array.isArray(options.collector)
          ? options.collector
          : [options.collector]
        : [];
      const raw = await this.runtime.callFunction(
        'ExtractSpeechPatterns',
        {
          content: content,
        },
        this.ctxManager.cloneContext(),
        options.tb?.__tb(),
        options.clientRegistry,
        collector,
      );
      return raw.parsed(false) as SpeechExtractionResult;
    } catch (error) {
      throw toBamlError(error);
    }
  }
}

class BamlStreamClient {
  private runtime: BamlRuntime;
  private ctxManager: BamlCtxManager;
  private bamlOptions: BamlCallOptions;

  constructor(runtime: BamlRuntime, ctxManager: BamlCtxManager, bamlOptions?: BamlCallOptions) {
    this.runtime = runtime;
    this.ctxManager = ctxManager;
    this.bamlOptions = bamlOptions || {};
  }

  AnalyzeEmotions(
    text: string,
    __baml_options__?: {
      tb?: TypeBuilder;
      clientRegistry?: ClientRegistry;
      collector?: Collector | Collector[];
    },
  ): BamlStream<partial_types.EmotionAnalysis, EmotionAnalysis> {
    try {
      const options = { ...this.bamlOptions, ...(__baml_options__ || {}) };
      const collector = options.collector
        ? Array.isArray(options.collector)
          ? options.collector
          : [options.collector]
        : [];
      const raw = this.runtime.streamFunction(
        'AnalyzeEmotions',
        {
          text: text,
        },
        undefined,
        this.ctxManager.cloneContext(),
        options.tb?.__tb(),
        options.clientRegistry,
        collector,
      );
      return new BamlStream<partial_types.EmotionAnalysis, EmotionAnalysis>(
        raw,
        (a): partial_types.EmotionAnalysis => a,
        (a): EmotionAnalysis => a,
        this.ctxManager.cloneContext(),
      );
    } catch (error) {
      throw toBamlError(error);
    }
  }

  AnalyzePersonalityDynamics(
    recentObservations: PersonalityObservation[],
    historicalContext?: string | null,
    __baml_options__?: {
      tb?: TypeBuilder;
      clientRegistry?: ClientRegistry;
      collector?: Collector | Collector[];
    },
  ): BamlStream<
    (partial_types.PersonalityDynamicsAnalysis | null)[],
    PersonalityDynamicsAnalysis[]
  > {
    try {
      const options = { ...this.bamlOptions, ...(__baml_options__ || {}) };
      const collector = options.collector
        ? Array.isArray(options.collector)
          ? options.collector
          : [options.collector]
        : [];
      const raw = this.runtime.streamFunction(
        'AnalyzePersonalityDynamics',
        {
          recentObservations: recentObservations,
          historicalContext: historicalContext ?? null,
        },
        undefined,
        this.ctxManager.cloneContext(),
        options.tb?.__tb(),
        options.clientRegistry,
        collector,
      );
      return new BamlStream<
        (partial_types.PersonalityDynamicsAnalysis | null)[],
        PersonalityDynamicsAnalysis[]
      >(
        raw,
        (a): (partial_types.PersonalityDynamicsAnalysis | null)[] => a,
        (a): PersonalityDynamicsAnalysis[] => a,
        this.ctxManager.cloneContext(),
      );
    } catch (error) {
      throw toBamlError(error);
    }
  }

  EstimatePADValues(
    emotionName: string,
    context: string,
    __baml_options__?: {
      tb?: TypeBuilder;
      clientRegistry?: ClientRegistry;
      collector?: Collector | Collector[];
    },
  ): BamlStream<partial_types.PADValues, PADValues> {
    try {
      const options = { ...this.bamlOptions, ...(__baml_options__ || {}) };
      const collector = options.collector
        ? Array.isArray(options.collector)
          ? options.collector
          : [options.collector]
        : [];
      const raw = this.runtime.streamFunction(
        'EstimatePADValues',
        {
          emotionName: emotionName,
          context: context,
        },
        undefined,
        this.ctxManager.cloneContext(),
        options.tb?.__tb(),
        options.clientRegistry,
        collector,
      );
      return new BamlStream<partial_types.PADValues, PADValues>(
        raw,
        (a): partial_types.PADValues => a,
        (a): PADValues => a,
        this.ctxManager.cloneContext(),
      );
    } catch (error) {
      throw toBamlError(error);
    }
  }

  ExtractDesiresAndBoundaries(
    content: string,
    __baml_options__?: {
      tb?: TypeBuilder;
      clientRegistry?: ClientRegistry;
      collector?: Collector | Collector[];
    },
  ): BamlStream<partial_types.DesiresExtractionResult, DesiresExtractionResult> {
    try {
      const options = { ...this.bamlOptions, ...(__baml_options__ || {}) };
      const collector = options.collector
        ? Array.isArray(options.collector)
          ? options.collector
          : [options.collector]
        : [];
      const raw = this.runtime.streamFunction(
        'ExtractDesiresAndBoundaries',
        {
          content: content,
        },
        undefined,
        this.ctxManager.cloneContext(),
        options.tb?.__tb(),
        options.clientRegistry,
        collector,
      );
      return new BamlStream<partial_types.DesiresExtractionResult, DesiresExtractionResult>(
        raw,
        (a): partial_types.DesiresExtractionResult => a,
        (a): DesiresExtractionResult => a,
        this.ctxManager.cloneContext(),
      );
    } catch (error) {
      throw toBamlError(error);
    }
  }

  ExtractEmotionalJourney(
    messages: string[],
    __baml_options__?: {
      tb?: TypeBuilder;
      clientRegistry?: ClientRegistry;
      collector?: Collector | Collector[];
    },
  ): BamlStream<(partial_types.EmotionalTransition | null)[], EmotionalTransition[]> {
    try {
      const options = { ...this.bamlOptions, ...(__baml_options__ || {}) };
      const collector = options.collector
        ? Array.isArray(options.collector)
          ? options.collector
          : [options.collector]
        : [];
      const raw = this.runtime.streamFunction(
        'ExtractEmotionalJourney',
        {
          messages: messages,
        },
        undefined,
        this.ctxManager.cloneContext(),
        options.tb?.__tb(),
        options.clientRegistry,
        collector,
      );
      return new BamlStream<(partial_types.EmotionalTransition | null)[], EmotionalTransition[]>(
        raw,
        (a): (partial_types.EmotionalTransition | null)[] => a,
        (a): EmotionalTransition[] => a,
        this.ctxManager.cloneContext(),
      );
    } catch (error) {
      throw toBamlError(error);
    }
  }

  ExtractEmotionalPatterns(
    content: string,
    __baml_options__?: {
      tb?: TypeBuilder;
      clientRegistry?: ClientRegistry;
      collector?: Collector | Collector[];
    },
  ): BamlStream<partial_types.EmotionalExtractionResult, EmotionalExtractionResult> {
    try {
      const options = { ...this.bamlOptions, ...(__baml_options__ || {}) };
      const collector = options.collector
        ? Array.isArray(options.collector)
          ? options.collector
          : [options.collector]
        : [];
      const raw = this.runtime.streamFunction(
        'ExtractEmotionalPatterns',
        {
          content: content,
        },
        undefined,
        this.ctxManager.cloneContext(),
        options.tb?.__tb(),
        options.clientRegistry,
        collector,
      );
      return new BamlStream<partial_types.EmotionalExtractionResult, EmotionalExtractionResult>(
        raw,
        (a): partial_types.EmotionalExtractionResult => a,
        (a): EmotionalExtractionResult => a,
        this.ctxManager.cloneContext(),
      );
    } catch (error) {
      throw toBamlError(error);
    }
  }

  ExtractIdentityComponents(
    content: string,
    __baml_options__?: {
      tb?: TypeBuilder;
      clientRegistry?: ClientRegistry;
      collector?: Collector | Collector[];
    },
  ): BamlStream<partial_types.IdentityExtractionResult, IdentityExtractionResult> {
    try {
      const options = { ...this.bamlOptions, ...(__baml_options__ || {}) };
      const collector = options.collector
        ? Array.isArray(options.collector)
          ? options.collector
          : [options.collector]
        : [];
      const raw = this.runtime.streamFunction(
        'ExtractIdentityComponents',
        {
          content: content,
        },
        undefined,
        this.ctxManager.cloneContext(),
        options.tb?.__tb(),
        options.clientRegistry,
        collector,
      );
      return new BamlStream<partial_types.IdentityExtractionResult, IdentityExtractionResult>(
        raw,
        (a): partial_types.IdentityExtractionResult => a,
        (a): IdentityExtractionResult => a,
        this.ctxManager.cloneContext(),
      );
    } catch (error) {
      throw toBamlError(error);
    }
  }

  ExtractPersonalityObservations(
    content: string,
    recentHistory?: string | null,
    __baml_options__?: {
      tb?: TypeBuilder;
      clientRegistry?: ClientRegistry;
      collector?: Collector | Collector[];
    },
  ): BamlStream<partial_types.PersonalityObservationResult, PersonalityObservationResult> {
    try {
      const options = { ...this.bamlOptions, ...(__baml_options__ || {}) };
      const collector = options.collector
        ? Array.isArray(options.collector)
          ? options.collector
          : [options.collector]
        : [];
      const raw = this.runtime.streamFunction(
        'ExtractPersonalityObservations',
        {
          content: content,
          recentHistory: recentHistory ?? null,
        },
        undefined,
        this.ctxManager.cloneContext(),
        options.tb?.__tb(),
        options.clientRegistry,
        collector,
      );
      return new BamlStream<
        partial_types.PersonalityObservationResult,
        PersonalityObservationResult
      >(
        raw,
        (a): partial_types.PersonalityObservationResult => a,
        (a): PersonalityObservationResult => a,
        this.ctxManager.cloneContext(),
      );
    } catch (error) {
      throw toBamlError(error);
    }
  }

  ExtractPhysicalAttributes(
    content: string,
    __baml_options__?: {
      tb?: TypeBuilder;
      clientRegistry?: ClientRegistry;
      collector?: Collector | Collector[];
    },
  ): BamlStream<partial_types.PhysicalExtractionResult, PhysicalExtractionResult> {
    try {
      const options = { ...this.bamlOptions, ...(__baml_options__ || {}) };
      const collector = options.collector
        ? Array.isArray(options.collector)
          ? options.collector
          : [options.collector]
        : [];
      const raw = this.runtime.streamFunction(
        'ExtractPhysicalAttributes',
        {
          content: content,
        },
        undefined,
        this.ctxManager.cloneContext(),
        options.tb?.__tb(),
        options.clientRegistry,
        collector,
      );
      return new BamlStream<partial_types.PhysicalExtractionResult, PhysicalExtractionResult>(
        raw,
        (a): partial_types.PhysicalExtractionResult => a,
        (a): PhysicalExtractionResult => a,
        this.ctxManager.cloneContext(),
      );
    } catch (error) {
      throw toBamlError(error);
    }
  }

  ExtractResume(
    resume: string,
    __baml_options__?: {
      tb?: TypeBuilder;
      clientRegistry?: ClientRegistry;
      collector?: Collector | Collector[];
    },
  ): BamlStream<partial_types.Resume, Resume> {
    try {
      const options = { ...this.bamlOptions, ...(__baml_options__ || {}) };
      const collector = options.collector
        ? Array.isArray(options.collector)
          ? options.collector
          : [options.collector]
        : [];
      const raw = this.runtime.streamFunction(
        'ExtractResume',
        {
          resume: resume,
        },
        undefined,
        this.ctxManager.cloneContext(),
        options.tb?.__tb(),
        options.clientRegistry,
        collector,
      );
      return new BamlStream<partial_types.Resume, Resume>(
        raw,
        (a): partial_types.Resume => a,
        (a): Resume => a,
        this.ctxManager.cloneContext(),
      );
    } catch (error) {
      throw toBamlError(error);
    }
  }

  ExtractSpeechPatterns(
    content: string,
    __baml_options__?: {
      tb?: TypeBuilder;
      clientRegistry?: ClientRegistry;
      collector?: Collector | Collector[];
    },
  ): BamlStream<partial_types.SpeechExtractionResult, SpeechExtractionResult> {
    try {
      const options = { ...this.bamlOptions, ...(__baml_options__ || {}) };
      const collector = options.collector
        ? Array.isArray(options.collector)
          ? options.collector
          : [options.collector]
        : [];
      const raw = this.runtime.streamFunction(
        'ExtractSpeechPatterns',
        {
          content: content,
        },
        undefined,
        this.ctxManager.cloneContext(),
        options.tb?.__tb(),
        options.clientRegistry,
        collector,
      );
      return new BamlStream<partial_types.SpeechExtractionResult, SpeechExtractionResult>(
        raw,
        (a): partial_types.SpeechExtractionResult => a,
        (a): SpeechExtractionResult => a,
        this.ctxManager.cloneContext(),
      );
    } catch (error) {
      throw toBamlError(error);
    }
  }
}

export const b = new BamlAsyncClient(
  DO_NOT_USE_DIRECTLY_UNLESS_YOU_KNOW_WHAT_YOURE_DOING_RUNTIME,
  DO_NOT_USE_DIRECTLY_UNLESS_YOU_KNOW_WHAT_YOURE_DOING_CTX,
);
