/*************************************************************************************************

Welcome to Baml! To use this generated code, please run one of the following:

$ npm install @boundaryml/baml
$ yarn add @boundaryml/baml
$ pnpm add @boundaryml/baml

*************************************************************************************************/

// This file was generated by BAML: do not edit it. Instead, edit the BAML
// files and re-generate this code.
//
/* eslint-disable */
// tslint:disable
// @ts-nocheck
// biome-ignore format: autogenerated code
import type { BamlRuntime, BamlCtxManager, ClientRegistry, Image, Audio, Collector } from "@boundaryml/baml"
import { toBamlError } from "@boundaryml/baml"
import type { Checked, Check } from "./types"
import type { partial_types } from "./partial_types"
import type * as types from "./types"
import type {CurrentStateAnalysis, Desire, DesiresExtractionResult, DetectedEmotion, EmergingPattern, EmotionAnalysis, EmotionMetadata, EmotionalExtractionResult, EmotionalTransition, EventTriggeredChange, IdentityComponent, IdentityExtractionResult, PADValues, PersonalityContext, PersonalityDynamicsAnalysis, PersonalityObservation, PersonalityObservationResult, PersonalityTrait, PhysicalAttribute, PhysicalExtractionResult, Preference, Resume, SpeechExtractionResult, SpeechPattern, StateDeviation, TemporalDynamics, VariabilityPattern} from "./types"
import type TypeBuilder from "./type_builder"

export class LlmResponseParser {
  constructor(private runtime: BamlRuntime, private ctxManager: BamlCtxManager) {}

  
  AnalyzeEmotions(
      llmResponse: string,
      __baml_options__?: { tb?: TypeBuilder, clientRegistry?: ClientRegistry }
  ): EmotionAnalysis {
    try {
      return this.runtime.parseLlmResponse(
        "AnalyzeEmotions",
        llmResponse,
        false,
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __baml_options__?.clientRegistry,
      ) as EmotionAnalysis
    } catch (error) {
      throw toBamlError(error);
    }
  }
  
  AnalyzePersonalityDynamics(
      llmResponse: string,
      __baml_options__?: { tb?: TypeBuilder, clientRegistry?: ClientRegistry }
  ): PersonalityDynamicsAnalysis[] {
    try {
      return this.runtime.parseLlmResponse(
        "AnalyzePersonalityDynamics",
        llmResponse,
        false,
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __baml_options__?.clientRegistry,
      ) as PersonalityDynamicsAnalysis[]
    } catch (error) {
      throw toBamlError(error);
    }
  }
  
  EstimatePADValues(
      llmResponse: string,
      __baml_options__?: { tb?: TypeBuilder, clientRegistry?: ClientRegistry }
  ): PADValues {
    try {
      return this.runtime.parseLlmResponse(
        "EstimatePADValues",
        llmResponse,
        false,
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __baml_options__?.clientRegistry,
      ) as PADValues
    } catch (error) {
      throw toBamlError(error);
    }
  }
  
  ExtractDesiresAndBoundaries(
      llmResponse: string,
      __baml_options__?: { tb?: TypeBuilder, clientRegistry?: ClientRegistry }
  ): DesiresExtractionResult {
    try {
      return this.runtime.parseLlmResponse(
        "ExtractDesiresAndBoundaries",
        llmResponse,
        false,
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __baml_options__?.clientRegistry,
      ) as DesiresExtractionResult
    } catch (error) {
      throw toBamlError(error);
    }
  }
  
  ExtractEmotionalJourney(
      llmResponse: string,
      __baml_options__?: { tb?: TypeBuilder, clientRegistry?: ClientRegistry }
  ): EmotionalTransition[] {
    try {
      return this.runtime.parseLlmResponse(
        "ExtractEmotionalJourney",
        llmResponse,
        false,
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __baml_options__?.clientRegistry,
      ) as EmotionalTransition[]
    } catch (error) {
      throw toBamlError(error);
    }
  }
  
  ExtractEmotionalPatterns(
      llmResponse: string,
      __baml_options__?: { tb?: TypeBuilder, clientRegistry?: ClientRegistry }
  ): EmotionalExtractionResult {
    try {
      return this.runtime.parseLlmResponse(
        "ExtractEmotionalPatterns",
        llmResponse,
        false,
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __baml_options__?.clientRegistry,
      ) as EmotionalExtractionResult
    } catch (error) {
      throw toBamlError(error);
    }
  }
  
  ExtractIdentityComponents(
      llmResponse: string,
      __baml_options__?: { tb?: TypeBuilder, clientRegistry?: ClientRegistry }
  ): IdentityExtractionResult {
    try {
      return this.runtime.parseLlmResponse(
        "ExtractIdentityComponents",
        llmResponse,
        false,
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __baml_options__?.clientRegistry,
      ) as IdentityExtractionResult
    } catch (error) {
      throw toBamlError(error);
    }
  }
  
  ExtractPersonalityObservations(
      llmResponse: string,
      __baml_options__?: { tb?: TypeBuilder, clientRegistry?: ClientRegistry }
  ): PersonalityObservationResult {
    try {
      return this.runtime.parseLlmResponse(
        "ExtractPersonalityObservations",
        llmResponse,
        false,
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __baml_options__?.clientRegistry,
      ) as PersonalityObservationResult
    } catch (error) {
      throw toBamlError(error);
    }
  }
  
  ExtractPhysicalAttributes(
      llmResponse: string,
      __baml_options__?: { tb?: TypeBuilder, clientRegistry?: ClientRegistry }
  ): PhysicalExtractionResult {
    try {
      return this.runtime.parseLlmResponse(
        "ExtractPhysicalAttributes",
        llmResponse,
        false,
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __baml_options__?.clientRegistry,
      ) as PhysicalExtractionResult
    } catch (error) {
      throw toBamlError(error);
    }
  }
  
  ExtractResume(
      llmResponse: string,
      __baml_options__?: { tb?: TypeBuilder, clientRegistry?: ClientRegistry }
  ): Resume {
    try {
      return this.runtime.parseLlmResponse(
        "ExtractResume",
        llmResponse,
        false,
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __baml_options__?.clientRegistry,
      ) as Resume
    } catch (error) {
      throw toBamlError(error);
    }
  }
  
  ExtractSpeechPatterns(
      llmResponse: string,
      __baml_options__?: { tb?: TypeBuilder, clientRegistry?: ClientRegistry }
  ): SpeechExtractionResult {
    try {
      return this.runtime.parseLlmResponse(
        "ExtractSpeechPatterns",
        llmResponse,
        false,
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __baml_options__?.clientRegistry,
      ) as SpeechExtractionResult
    } catch (error) {
      throw toBamlError(error);
    }
  }
  
}

export class LlmStreamParser {
  constructor(private runtime: BamlRuntime, private ctxManager: BamlCtxManager) {}

  
  AnalyzeEmotions(
      llmResponse: string,
      __baml_options__?: { tb?: TypeBuilder, clientRegistry?: ClientRegistry }
  ): partial_types.EmotionAnalysis {
    try {
      return this.runtime.parseLlmResponse(
        "AnalyzeEmotions",
        llmResponse,
        true,
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __baml_options__?.clientRegistry,
      ) as partial_types.EmotionAnalysis
    } catch (error) {
      throw toBamlError(error);
    }
  }
  
  AnalyzePersonalityDynamics(
      llmResponse: string,
      __baml_options__?: { tb?: TypeBuilder, clientRegistry?: ClientRegistry }
  ): (partial_types.PersonalityDynamicsAnalysis | null)[] {
    try {
      return this.runtime.parseLlmResponse(
        "AnalyzePersonalityDynamics",
        llmResponse,
        true,
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __baml_options__?.clientRegistry,
      ) as (partial_types.PersonalityDynamicsAnalysis | null)[]
    } catch (error) {
      throw toBamlError(error);
    }
  }
  
  EstimatePADValues(
      llmResponse: string,
      __baml_options__?: { tb?: TypeBuilder, clientRegistry?: ClientRegistry }
  ): partial_types.PADValues {
    try {
      return this.runtime.parseLlmResponse(
        "EstimatePADValues",
        llmResponse,
        true,
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __baml_options__?.clientRegistry,
      ) as partial_types.PADValues
    } catch (error) {
      throw toBamlError(error);
    }
  }
  
  ExtractDesiresAndBoundaries(
      llmResponse: string,
      __baml_options__?: { tb?: TypeBuilder, clientRegistry?: ClientRegistry }
  ): partial_types.DesiresExtractionResult {
    try {
      return this.runtime.parseLlmResponse(
        "ExtractDesiresAndBoundaries",
        llmResponse,
        true,
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __baml_options__?.clientRegistry,
      ) as partial_types.DesiresExtractionResult
    } catch (error) {
      throw toBamlError(error);
    }
  }
  
  ExtractEmotionalJourney(
      llmResponse: string,
      __baml_options__?: { tb?: TypeBuilder, clientRegistry?: ClientRegistry }
  ): (partial_types.EmotionalTransition | null)[] {
    try {
      return this.runtime.parseLlmResponse(
        "ExtractEmotionalJourney",
        llmResponse,
        true,
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __baml_options__?.clientRegistry,
      ) as (partial_types.EmotionalTransition | null)[]
    } catch (error) {
      throw toBamlError(error);
    }
  }
  
  ExtractEmotionalPatterns(
      llmResponse: string,
      __baml_options__?: { tb?: TypeBuilder, clientRegistry?: ClientRegistry }
  ): partial_types.EmotionalExtractionResult {
    try {
      return this.runtime.parseLlmResponse(
        "ExtractEmotionalPatterns",
        llmResponse,
        true,
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __baml_options__?.clientRegistry,
      ) as partial_types.EmotionalExtractionResult
    } catch (error) {
      throw toBamlError(error);
    }
  }
  
  ExtractIdentityComponents(
      llmResponse: string,
      __baml_options__?: { tb?: TypeBuilder, clientRegistry?: ClientRegistry }
  ): partial_types.IdentityExtractionResult {
    try {
      return this.runtime.parseLlmResponse(
        "ExtractIdentityComponents",
        llmResponse,
        true,
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __baml_options__?.clientRegistry,
      ) as partial_types.IdentityExtractionResult
    } catch (error) {
      throw toBamlError(error);
    }
  }
  
  ExtractPersonalityObservations(
      llmResponse: string,
      __baml_options__?: { tb?: TypeBuilder, clientRegistry?: ClientRegistry }
  ): partial_types.PersonalityObservationResult {
    try {
      return this.runtime.parseLlmResponse(
        "ExtractPersonalityObservations",
        llmResponse,
        true,
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __baml_options__?.clientRegistry,
      ) as partial_types.PersonalityObservationResult
    } catch (error) {
      throw toBamlError(error);
    }
  }
  
  ExtractPhysicalAttributes(
      llmResponse: string,
      __baml_options__?: { tb?: TypeBuilder, clientRegistry?: ClientRegistry }
  ): partial_types.PhysicalExtractionResult {
    try {
      return this.runtime.parseLlmResponse(
        "ExtractPhysicalAttributes",
        llmResponse,
        true,
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __baml_options__?.clientRegistry,
      ) as partial_types.PhysicalExtractionResult
    } catch (error) {
      throw toBamlError(error);
    }
  }
  
  ExtractResume(
      llmResponse: string,
      __baml_options__?: { tb?: TypeBuilder, clientRegistry?: ClientRegistry }
  ): partial_types.Resume {
    try {
      return this.runtime.parseLlmResponse(
        "ExtractResume",
        llmResponse,
        true,
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __baml_options__?.clientRegistry,
      ) as partial_types.Resume
    } catch (error) {
      throw toBamlError(error);
    }
  }
  
  ExtractSpeechPatterns(
      llmResponse: string,
      __baml_options__?: { tb?: TypeBuilder, clientRegistry?: ClientRegistry }
  ): partial_types.SpeechExtractionResult {
    try {
      return this.runtime.parseLlmResponse(
        "ExtractSpeechPatterns",
        llmResponse,
        true,
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __baml_options__?.clientRegistry,
      ) as partial_types.SpeechExtractionResult
    } catch (error) {
      throw toBamlError(error);
    }
  }
  
}