/*************************************************************************************************

Welcome to Baml! To use this generated code, please run one of the following:

$ npm install @boundaryml/baml
$ yarn add @boundaryml/baml
$ pnpm add @boundaryml/baml

*************************************************************************************************/

// This file was generated by BAML: do not edit it. Instead, edit the BAML
// files and re-generate this code.
//
/* eslint-disable */
// tslint:disable
// @ts-nocheck
// biome-ignore format: autogenerated code
import type { Image, Audio } from "@boundaryml/baml"
import type { Checked, Check } from "./types"
import type {  Boundary,  CurrentStateAnalysis,  Desire,  DesiresExtractionResult,  DetectedEmotion,  EmergingPattern,  EmotionAnalysis,  EmotionMetadata,  EmotionalExtractionResult,  EmotionalTransition,  EventTriggeredChange,  IdentityComponent,  IdentityExtractionResult,  PADValues,  PersonalityContext,  PersonalityDynamicsAnalysis,  PersonalityObservation,  PersonalityObservationResult,  PersonalityTrait,  PhysicalAttribute,  PhysicalExtractionResult,  Preference,  Resume,  SpeechExtractionResult,  SpeechPattern,  StateDeviation,  TemporalDynamics,  VariabilityPattern } from "./types"
import type * as types from "./types"

/******************************************************************************
*
*  These types are used for streaming, for when an instance of a type
*  is still being built up and any of its fields is not yet fully available.
*
******************************************************************************/

export interface StreamState<T> {
    value: T
    state: "Pending" | "Incomplete" | "Complete"
}

export namespace partial_types {
    
    export interface Boundary {
        boundaryTypeId: ((number | null) | null)
        boundaryDescription?: (string | null)
        firmness?: (number | null)
        appliesToEntityId: ((string | null) | null)
        contextSpecific: ((string | null) | null)
        violationResponse: ((string | null) | null)
    }
    
    export interface CurrentStateAnalysis {
        observedValue?: (number | null)
        distanceFromTypical: ((number | null) | null)
        returningToBaseline: ((boolean | null) | null)
    }
    
    export interface Desire {
        desireCategoryId: ((number | null) | null)
        desireDescription?: (string | null)
        currentIntensity?: (number | null)
        fulfillmentLevel?: (number | null)
        fulfillmentConditions?: (string | null)[]
        isSecret?: (boolean | null)
    }
    
    export interface DesiresExtractionResult {
        desires?: (partial_types.Desire | null)[]
        preferences?: (partial_types.Preference | null)[]
        boundaries?: (partial_types.Boundary | null)[]
    }
    
    export interface DetectedEmotion {
        emotionName?: (string | null)
        intensity?: (number | null)
        confidence?: (number | null)
        triggers?: (string | null)[]
        context: ((string | null) | null)
        isCustom?: (boolean | null)
    }
    
    export interface EmergingPattern {
        pattern?: (string | null)
        frequency?: (string | null)
        contexts?: (string | null)[]
    }
    
    export interface EmotionAnalysis {
        primaryEmotions?: (partial_types.DetectedEmotion | null)[]
        secondaryEmotions?: (partial_types.DetectedEmotion | null)[]
        padValues?: (partial_types.PADValues | null)
        emotionalComplexity?: (number | null)
        compoundEmotions?: (string | null)[]
        customEmotions?: (string | null)[]
        transitions?: (partial_types.EmotionalTransition | null)[]
        metadata?: (partial_types.EmotionMetadata | null)
    }
    
    export interface EmotionMetadata {
        hasIntimateContent?: (boolean | null)
        hasPhysicalResponse?: (boolean | null)
        emotionalIntensity?: (string | null)
    }
    
    export interface EmotionalExtractionResult {
        personalityTraits?: (partial_types.PersonalityTrait | null)[]
    }
    
    export interface EmotionalTransition {
        fromEmotion?: (string | null)
        toEmotion?: (string | null)
        trigger: ((string | null) | null)
        intensity?: (number | null)
    }
    
    export interface EventTriggeredChange {
        event?: (string | null)
        impactMagnitude?: (number | null)
        persistenceDuration: ((string | null) | null)
    }
    
    export interface IdentityComponent {
        componentType?: (string | null)
        content?: (string | null)
        importance?: (number | null)
        isNegotiable?: (boolean | null)
        formedThrough: ((string | null) | null)
    }
    
    export interface IdentityExtractionResult {
        components?: (partial_types.IdentityComponent | null)[]
    }
    
    export interface PADValues {
        pleasure?: (number | null)
        arousal?: (number | null)
        dominance?: (number | null)
    }
    
    export interface PersonalityContext {
        situation: ((string | null) | null)
        interactionPartner: ((string | null) | null)
        emotionalState: ((string | null) | null)
        trigger: ((string | null) | null)
    }
    
    export interface PersonalityDynamicsAnalysis {
        traitDimension?: (string | null)
        currentState?: (partial_types.CurrentStateAnalysis | null)
        variabilityPattern?: (partial_types.VariabilityPattern | null)
        temporalDynamics?: (partial_types.TemporalDynamics | null)
    }
    
    export interface PersonalityObservation {
        traitDimension?: (string | null)
        observedValue?: (number | null)
        confidence?: (number | null)
        situation: ((string | null) | null)
        interactionPartner: ((string | null) | null)
        emotionalState: ((string | null) | null)
        trigger: ((string | null) | null)
        evidence?: (string | null)[]
    }
    
    export interface PersonalityObservationResult {
        observations?: (partial_types.PersonalityObservation | null)[]
        stateDeviations?: (partial_types.StateDeviation | null)[]
        emergingPatterns?: (partial_types.EmergingPattern | null)[]
    }
    
    export interface PersonalityTrait {
        traitCategory?: (string | null)
        traitName?: (string | null)
        baselineValue?: (number | null)
        currentValue?: (number | null)
        isCoreTrait?: (boolean | null)
        flexibility?: (number | null)
    }
    
    export interface PhysicalAttribute {
        bodyPartId: ((number | null) | null)
        attributeType?: (string | null)
        attributeValue?: (string | null)
        isPermanent?: (boolean | null)
        context: ((string | null) | null)
    }
    
    export interface PhysicalExtractionResult {
        attributes?: (partial_types.PhysicalAttribute | null)[]
    }
    
    export interface Preference {
        preferenceCategory?: (string | null)
        specificItem?: (string | null)
        preferenceType?: (string | null)
        intensity?: (number | null)
        reason: ((string | null) | null)
    }
    
    export interface Resume {
        name?: (string | null)
        email?: (string | null)
        experience?: (string | null)[]
        skills?: (string | null)[]
    }
    
    export interface SpeechExtractionResult {
        speechPatterns?: (partial_types.SpeechPattern | null)[]
    }
    
    export interface SpeechPattern {
        patternType?: (string | null)
        textPattern?: (string | null)
        frequency?: (number | null)
        emotionalContexts?: (string | null)[]
        socialContexts?: (string | null)[]
        variations?: (string | null)[]
    }
    
    export interface StateDeviation {
        dimension?: (string | null)
        deviationMagnitude?: (number | null)
        possibleCause: ((string | null) | null)
    }
    
    export interface TemporalDynamics {
        trend: ((string | null) | null)
        cyclicalPatterns: ((string | null) | null)
        eventTriggeredChanges?: (partial_types.EventTriggeredChange | null)[]
    }
    
    export interface VariabilityPattern {
        recentRange: ((number | null) | null)
        contextsWithHighVariation?: (string | null)[]
        contextsWithLowVariation?: (string | null)[]
    }
    
}