/*************************************************************************************************

Welcome to Baml! To use this generated code, please run one of the following:

$ npm install @boundaryml/baml
$ yarn add @boundaryml/baml
$ pnpm add @boundaryml/baml

*************************************************************************************************/

// This file was generated by BAML: do not edit it. Instead, edit the BAML
// files and re-generate this code.
//
/* eslint-disable */
// tslint:disable
// @ts-nocheck
// biome-ignore format: autogenerated code
import type { Image, Audio } from "@boundaryml/baml"
import type { Checked, Check } from "./types"
import type {  DetectedEmotion,  EmotionAnalysis,  EmotionMetadata,  EmotionalTransition,  PADValues,  Resume } from "./types"
import type * as types from "./types"

/******************************************************************************
*
*  These types are used for streaming, for when an instance of a type
*  is still being built up and any of its fields is not yet fully available.
*
******************************************************************************/

export interface StreamState<T> {
    value: T
    state: "Pending" | "Incomplete" | "Complete"
}

export namespace partial_types {
    
    export interface DetectedEmotion {
        emotionName?: (string | null)
        intensity?: (number | null)
        confidence?: (number | null)
        triggers?: (string | null)[]
        context: ((string | null) | null)
        isCustom?: (boolean | null)
    }
    
    export interface EmotionAnalysis {
        primaryEmotions?: (partial_types.DetectedEmotion | null)[]
        secondaryEmotions?: (partial_types.DetectedEmotion | null)[]
        padValues?: (partial_types.PADValues | null)
        emotionalComplexity?: (number | null)
        compoundEmotions?: (string | null)[]
        customEmotions?: (string | null)[]
        transitions?: (partial_types.EmotionalTransition | null)[]
        metadata?: (partial_types.EmotionMetadata | null)
    }
    
    export interface EmotionMetadata {
        hasIntimateContent?: (boolean | null)
        hasPhysicalResponse?: (boolean | null)
        emotionalIntensity?: (string | null)
    }
    
    export interface EmotionalTransition {
        fromEmotion?: (string | null)
        toEmotion?: (string | null)
        trigger: ((string | null) | null)
        intensity?: (number | null)
    }
    
    export interface PADValues {
        pleasure?: (number | null)
        arousal?: (number | null)
        dominance?: (number | null)
    }
    
    export interface Resume {
        name?: (string | null)
        email?: (string | null)
        experience?: (string | null)[]
        skills?: (string | null)[]
    }
    
}