/*************************************************************************************************

Welcome to Baml! To use this generated code, please run one of the following:

$ npm install @boundaryml/baml
$ yarn add @boundaryml/baml
$ pnpm add @boundaryml/baml

*************************************************************************************************/

// This file was generated by BAML: do not edit it. Instead, edit the BAML
// files and re-generate this code.
//
/* eslint-disable */
// tslint:disable
// @ts-nocheck
// biome-ignore format: autogenerated code
import type { Image, Audio } from "@boundaryml/baml"

/**
 * Recursively partial type that can be null.
 *
 * @deprecated Use types from the `partial_types` namespace instead, which provides type-safe partial implementations
 * @template T The type to make recursively partial.
 */
export type RecursivePartialNull<T> = T extends object
    ? { [P in keyof T]?: RecursivePartialNull<T[P]> }
    : T | null;

export interface Checked<T,CheckName extends string = string> {
    value: T,
    checks: Record<CheckName, Check>,
}


export interface Check {
    name: string,
    expr: string
    status: "succeeded" | "failed"
}

export function all_succeeded<CheckName extends string>(checks: Record<CheckName, Check>): boolean {
    return get_checks(checks).every(check => check.status === "succeeded")
}

export function get_checks<CheckName extends string>(checks: Record<CheckName, Check>): Check[] {
    return Object.values(checks)
}
export interface CurrentStateAnalysis {
  observedValue: number
  distanceFromTypical?: number | null
  returningToBaseline?: boolean | null
  
}

export interface Desire {
  desireCategoryId?: number | null
  desireDescription: string
  currentIntensity: number
  fulfillmentLevel: number
  fulfillmentConditions: string[]
  isSecret: boolean
  
}

export interface DesiresExtractionResult {
  desires: Desire[]
  preferences: Preference[]
  
}

export interface DetectedEmotion {
  emotionName: string
  intensity: number
  confidence: number
  triggers: string[]
  context?: string | null
  isCustom: boolean
  
}

export interface EmergingPattern {
  pattern: string
  frequency: string
  contexts: string[]
  
}

export interface EmotionAnalysis {
  primaryEmotions: DetectedEmotion[]
  secondaryEmotions: DetectedEmotion[]
  padValues: PADValues
  emotionalComplexity: number
  compoundEmotions: string[]
  customEmotions: string[]
  transitions: EmotionalTransition[]
  metadata: EmotionMetadata
  
}

export interface EmotionMetadata {
  hasIntimateContent: boolean
  hasPhysicalResponse: boolean
  emotionalIntensity: string
  
}

export interface EmotionalExtractionResult {
  personalityTraits: PersonalityTrait[]
  
}

export interface EmotionalTransition {
  fromEmotion: string
  toEmotion: string
  trigger?: string | null
  intensity: number
  
}

export interface EventTriggeredChange {
  event: string
  impactMagnitude: number
  persistenceDuration?: string | null
  
}

export interface IdentityComponent {
  componentType: string
  content: string
  importance: number
  isNegotiable: boolean
  formedThrough?: string | null
  
}

export interface IdentityExtractionResult {
  components: IdentityComponent[]
  
}

export interface PADValues {
  pleasure: number
  arousal: number
  dominance: number
  
}

export interface PersonalityContext {
  situation?: string | null
  interactionPartner?: string | null
  emotionalState?: string | null
  trigger?: string | null
  
}

export interface PersonalityDynamicsAnalysis {
  traitDimension: string
  currentState: CurrentStateAnalysis
  variabilityPattern: VariabilityPattern
  temporalDynamics: TemporalDynamics
  
}

export interface PersonalityObservation {
  traitDimension: string
  observedValue: number
  confidence: number
  situation?: string | null
  interactionPartner?: string | null
  emotionalState?: string | null
  trigger?: string | null
  evidence: string[]
  
}

export interface PersonalityObservationResult {
  observations: PersonalityObservation[]
  stateDeviations: StateDeviation[]
  emergingPatterns: EmergingPattern[]
  
}

export interface PersonalityTrait {
  traitCategory: string
  traitName: string
  baselineValue: number
  currentValue: number
  isCoreTrait: boolean
  flexibility: number
  
}

export interface PhysicalAttribute {
  bodyPartId?: number | null
  attributeType: string
  attributeValue: string
  isPermanent: boolean
  context?: string | null
  
}

export interface PhysicalExtractionResult {
  attributes: PhysicalAttribute[]
  
}

export interface Preference {
  preferenceCategory: string
  specificItem: string
  preferenceType: string
  intensity: number
  reason?: string | null
  
}

export interface Resume {
  name: string
  email: string
  experience: string[]
  skills: string[]
  
}

export interface SpeechExtractionResult {
  speechPatterns: SpeechPattern[]
  
}

export interface SpeechPattern {
  patternType: string
  textPattern: string
  frequency: number
  emotionalContexts: string[]
  socialContexts: string[]
  variations: string[]
  
}

export interface StateDeviation {
  dimension: string
  deviationMagnitude: number
  possibleCause?: string | null
  
}

export interface TemporalDynamics {
  trend?: string | null
  cyclicalPatterns?: string | null
  eventTriggeredChanges: EventTriggeredChange[]
  
}

export interface VariabilityPattern {
  recentRange?: number | null
  contextsWithHighVariation: string[]
  contextsWithLowVariation: string[]
  
}
