/*************************************************************************************************

Welcome to Baml! To use this generated code, please run one of the following:

$ npm install @boundaryml/baml
$ yarn add @boundaryml/baml
$ pnpm add @boundaryml/baml

*************************************************************************************************/

// This file was generated by BAML: do not edit it. Instead, edit the BAML
// files and re-generate this code.
//
/* eslint-disable */
// tslint:disable
// @ts-nocheck
// biome-ignore format: autogenerated code
import { FieldType } from '@boundaryml/baml/native'
import { TypeBuilder as _TypeBuilder, EnumBuilder, EnumViewer, ClassBuilder, ClassViewer } from '@boundaryml/baml/type_builder'
import { DO_NOT_USE_DIRECTLY_UNLESS_YOU_KNOW_WHAT_YOURE_DOING_RUNTIME } from "./globals"

export default class TypeBuilder {
    private tb: _TypeBuilder;
    
    Boundary: ClassViewer<'Boundary', "boundaryTypeId" | "boundaryDescription" | "firmness" | "appliesToEntityId" | "contextSpecific" | "violationResponse">;
    
    CurrentStateAnalysis: ClassViewer<'CurrentStateAnalysis', "observedValue" | "distanceFromTypical" | "returningToBaseline">;
    
    Desire: ClassViewer<'Desire', "desireCategoryId" | "desireDescription" | "currentIntensity" | "fulfillmentLevel" | "fulfillmentConditions" | "isSecret">;
    
    DesiresExtractionResult: ClassViewer<'DesiresExtractionResult', "desires" | "preferences" | "boundaries">;
    
    DetectedEmotion: ClassViewer<'DetectedEmotion', "emotionName" | "intensity" | "confidence" | "triggers" | "context" | "isCustom">;
    
    EmergingPattern: ClassViewer<'EmergingPattern', "pattern" | "frequency" | "contexts">;
    
    EmotionAnalysis: ClassViewer<'EmotionAnalysis', "primaryEmotions" | "secondaryEmotions" | "padValues" | "emotionalComplexity" | "compoundEmotions" | "customEmotions" | "transitions" | "metadata">;
    
    EmotionMetadata: ClassViewer<'EmotionMetadata', "hasIntimateContent" | "hasPhysicalResponse" | "emotionalIntensity">;
    
    EmotionalExtractionResult: ClassViewer<'EmotionalExtractionResult', "personalityTraits">;
    
    EmotionalTransition: ClassViewer<'EmotionalTransition', "fromEmotion" | "toEmotion" | "trigger" | "intensity">;
    
    EventTriggeredChange: ClassViewer<'EventTriggeredChange', "event" | "impactMagnitude" | "persistenceDuration">;
    
    IdentityComponent: ClassViewer<'IdentityComponent', "componentType" | "content" | "importance" | "isNegotiable" | "formedThrough">;
    
    IdentityExtractionResult: ClassViewer<'IdentityExtractionResult', "components">;
    
    PADValues: ClassViewer<'PADValues', "pleasure" | "arousal" | "dominance">;
    
    PersonalityContext: ClassViewer<'PersonalityContext', "situation" | "interactionPartner" | "emotionalState" | "trigger">;
    
    PersonalityDynamicsAnalysis: ClassViewer<'PersonalityDynamicsAnalysis', "traitDimension" | "currentState" | "variabilityPattern" | "temporalDynamics">;
    
    PersonalityObservation: ClassViewer<'PersonalityObservation', "traitDimension" | "observedValue" | "confidence" | "situation" | "interactionPartner" | "emotionalState" | "trigger" | "evidence">;
    
    PersonalityObservationResult: ClassViewer<'PersonalityObservationResult', "observations" | "stateDeviations" | "emergingPatterns">;
    
    PersonalityTrait: ClassViewer<'PersonalityTrait', "traitCategory" | "traitName" | "baselineValue" | "currentValue" | "isCoreTrait" | "flexibility">;
    
    PhysicalAttribute: ClassViewer<'PhysicalAttribute', "bodyPartId" | "attributeType" | "attributeValue" | "isPermanent" | "context">;
    
    PhysicalExtractionResult: ClassViewer<'PhysicalExtractionResult', "attributes">;
    
    Preference: ClassViewer<'Preference', "preferenceCategory" | "specificItem" | "preferenceType" | "intensity" | "reason">;
    
    Resume: ClassViewer<'Resume', "name" | "email" | "experience" | "skills">;
    
    SpeechExtractionResult: ClassViewer<'SpeechExtractionResult', "speechPatterns">;
    
    SpeechPattern: ClassViewer<'SpeechPattern', "patternType" | "textPattern" | "frequency" | "emotionalContexts" | "socialContexts" | "variations">;
    
    StateDeviation: ClassViewer<'StateDeviation', "dimension" | "deviationMagnitude" | "possibleCause">;
    
    TemporalDynamics: ClassViewer<'TemporalDynamics', "trend" | "cyclicalPatterns" | "eventTriggeredChanges">;
    
    VariabilityPattern: ClassViewer<'VariabilityPattern', "recentRange" | "contextsWithHighVariation" | "contextsWithLowVariation">;
    
    

    constructor() {
        this.tb = new _TypeBuilder({
          classes: new Set([
            "Boundary","CurrentStateAnalysis","Desire","DesiresExtractionResult","DetectedEmotion","EmergingPattern","EmotionAnalysis","EmotionMetadata","EmotionalExtractionResult","EmotionalTransition","EventTriggeredChange","IdentityComponent","IdentityExtractionResult","PADValues","PersonalityContext","PersonalityDynamicsAnalysis","PersonalityObservation","PersonalityObservationResult","PersonalityTrait","PhysicalAttribute","PhysicalExtractionResult","Preference","Resume","SpeechExtractionResult","SpeechPattern","StateDeviation","TemporalDynamics","VariabilityPattern",
          ]),
          enums: new Set([
            
          ]),
          runtime: DO_NOT_USE_DIRECTLY_UNLESS_YOU_KNOW_WHAT_YOURE_DOING_RUNTIME
        });
        
        this.Boundary = this.tb.classViewer("Boundary", [
          "boundaryTypeId","boundaryDescription","firmness","appliesToEntityId","contextSpecific","violationResponse",
        ]);
        
        this.CurrentStateAnalysis = this.tb.classViewer("CurrentStateAnalysis", [
          "observedValue","distanceFromTypical","returningToBaseline",
        ]);
        
        this.Desire = this.tb.classViewer("Desire", [
          "desireCategoryId","desireDescription","currentIntensity","fulfillmentLevel","fulfillmentConditions","isSecret",
        ]);
        
        this.DesiresExtractionResult = this.tb.classViewer("DesiresExtractionResult", [
          "desires","preferences","boundaries",
        ]);
        
        this.DetectedEmotion = this.tb.classViewer("DetectedEmotion", [
          "emotionName","intensity","confidence","triggers","context","isCustom",
        ]);
        
        this.EmergingPattern = this.tb.classViewer("EmergingPattern", [
          "pattern","frequency","contexts",
        ]);
        
        this.EmotionAnalysis = this.tb.classViewer("EmotionAnalysis", [
          "primaryEmotions","secondaryEmotions","padValues","emotionalComplexity","compoundEmotions","customEmotions","transitions","metadata",
        ]);
        
        this.EmotionMetadata = this.tb.classViewer("EmotionMetadata", [
          "hasIntimateContent","hasPhysicalResponse","emotionalIntensity",
        ]);
        
        this.EmotionalExtractionResult = this.tb.classViewer("EmotionalExtractionResult", [
          "personalityTraits",
        ]);
        
        this.EmotionalTransition = this.tb.classViewer("EmotionalTransition", [
          "fromEmotion","toEmotion","trigger","intensity",
        ]);
        
        this.EventTriggeredChange = this.tb.classViewer("EventTriggeredChange", [
          "event","impactMagnitude","persistenceDuration",
        ]);
        
        this.IdentityComponent = this.tb.classViewer("IdentityComponent", [
          "componentType","content","importance","isNegotiable","formedThrough",
        ]);
        
        this.IdentityExtractionResult = this.tb.classViewer("IdentityExtractionResult", [
          "components",
        ]);
        
        this.PADValues = this.tb.classViewer("PADValues", [
          "pleasure","arousal","dominance",
        ]);
        
        this.PersonalityContext = this.tb.classViewer("PersonalityContext", [
          "situation","interactionPartner","emotionalState","trigger",
        ]);
        
        this.PersonalityDynamicsAnalysis = this.tb.classViewer("PersonalityDynamicsAnalysis", [
          "traitDimension","currentState","variabilityPattern","temporalDynamics",
        ]);
        
        this.PersonalityObservation = this.tb.classViewer("PersonalityObservation", [
          "traitDimension","observedValue","confidence","situation","interactionPartner","emotionalState","trigger","evidence",
        ]);
        
        this.PersonalityObservationResult = this.tb.classViewer("PersonalityObservationResult", [
          "observations","stateDeviations","emergingPatterns",
        ]);
        
        this.PersonalityTrait = this.tb.classViewer("PersonalityTrait", [
          "traitCategory","traitName","baselineValue","currentValue","isCoreTrait","flexibility",
        ]);
        
        this.PhysicalAttribute = this.tb.classViewer("PhysicalAttribute", [
          "bodyPartId","attributeType","attributeValue","isPermanent","context",
        ]);
        
        this.PhysicalExtractionResult = this.tb.classViewer("PhysicalExtractionResult", [
          "attributes",
        ]);
        
        this.Preference = this.tb.classViewer("Preference", [
          "preferenceCategory","specificItem","preferenceType","intensity","reason",
        ]);
        
        this.Resume = this.tb.classViewer("Resume", [
          "name","email","experience","skills",
        ]);
        
        this.SpeechExtractionResult = this.tb.classViewer("SpeechExtractionResult", [
          "speechPatterns",
        ]);
        
        this.SpeechPattern = this.tb.classViewer("SpeechPattern", [
          "patternType","textPattern","frequency","emotionalContexts","socialContexts","variations",
        ]);
        
        this.StateDeviation = this.tb.classViewer("StateDeviation", [
          "dimension","deviationMagnitude","possibleCause",
        ]);
        
        this.TemporalDynamics = this.tb.classViewer("TemporalDynamics", [
          "trend","cyclicalPatterns","eventTriggeredChanges",
        ]);
        
        this.VariabilityPattern = this.tb.classViewer("VariabilityPattern", [
          "recentRange","contextsWithHighVariation","contextsWithLowVariation",
        ]);
        
        
    }

    __tb() {
      return this.tb._tb();
    }

    string(): FieldType {
        return this.tb.string()
    }

    literalString(value: string): FieldType {
        return this.tb.literalString(value)
    }

    literalInt(value: number): FieldType {
        return this.tb.literalInt(value)
    }

    literalBool(value: boolean): FieldType {
        return this.tb.literalBool(value)
    }

    int(): FieldType {
        return this.tb.int()
    }

    float(): FieldType {
        return this.tb.float()
    }

    bool(): FieldType {
        return this.tb.bool()
    }

    list(type: FieldType): FieldType {
        return this.tb.list(type)
    }

    null(): FieldType {
        return this.tb.null()
    }

    map(key: FieldType, value: FieldType): FieldType {
        return this.tb.map(key, value)
    }

    union(types: FieldType[]): FieldType {
        return this.tb.union(types)
    }

    addClass<Name extends string>(name: Name): ClassBuilder<Name> {
        return this.tb.addClass(name);
    }

    addEnum<Name extends string>(name: Name): EnumBuilder<Name> {
        return this.tb.addEnum(name);
    }

    addBaml(baml: string): void {
        this.tb.addBaml(baml);
    }
}